import Container from "@/components/global/Container";
import Navbar from "@/components/navbar/Navbar";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
        title: "Next Store",
        description: "Generated by create next app",
};

export default function RootLayout({
        children,
}: Readonly<{
        children: React.ReactNode;
}>) {
        return (
                <html lang="en">
                        <body>
                                <Navbar />
                                <Container className="py-20">{children}</Container>
                        </body>
                </html>
        );
}
