import Container from "@/components/global/Container";
import Navbar from "@/components/navbar/Navbar";
import { Toaster } from "@/components/ui/toaster";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
export const metadata: Metadata = {
        title: "Next Store",
        description: "Generated by create next app",
};

export default function RootLayout({
        children,
}: Readonly<{
        children: React.ReactNode;
}>) {
        return (
                <ClerkProvider>
                        <html lang="en" suppressHydrationWarning>
                                <body className="relative">
                                        <Providers>
                                                <Navbar />
                                                <Container className="py-20">{children}</Container>
                                                <Toaster />
                                        </Providers>
                                </body>
                        </html>
                </ClerkProvider>
        );
}
